//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetBuddy.Category.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CategoryResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CategoryResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BudgetBuddy.Category.Resources.CategoryResource", typeof(CategoryResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not assign a category to another category.
        /// </summary>
        public static string AssigningCategoryToCategory {
            get {
                return ResourceManager.GetString("AssigningCategoryToCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups can not belong to another group.
        /// </summary>
        public static string AssigningGroupToGroup {
            get {
                return ResourceManager.GetString("AssigningGroupToGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category-group does not exist.
        /// </summary>
        public static string CategoryGroupDoesNotExist {
            get {
                return ResourceManager.GetString("CategoryGroupDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group id is missing.
        /// </summary>
        public static string GroupIdIsMissing {
            get {
                return ResourceManager.GetString("GroupIdIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups can not have goal amount.
        /// </summary>
        public static string GroupNeedNullGoalAmount {
            get {
                return ResourceManager.GetString("GroupNeedNullGoalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups can not have monthly amount.
        /// </summary>
        public static string GroupNeedNullMonthlyAmount {
            get {
                return ResourceManager.GetString("GroupNeedNullMonthlyAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly amount is required.
        /// </summary>
        public static string MonthlyAmountRequired {
            get {
                return ResourceManager.GetString("MonthlyAmountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal amount needs to be a positive number.
        /// </summary>
        public static string NeedPositiveGoalAmount {
            get {
                return ResourceManager.GetString("NeedPositiveGoalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly amount needs to be a positive number.
        /// </summary>
        public static string NeedPositiveMonthlyAmount {
            get {
                return ResourceManager.GetString("NeedPositiveMonthlyAmount", resourceCulture);
            }
        }
    }
}
